### ISSUE TITLE
Unable to conduct certain sequence alterations

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#456]
To fix (fails only for individual subfeatures, but full transcripts work when getting sequence):
- [x] if upstream of a UTR and deletion crosses, getGenome does not work
- [x] if spanning a CDS, these throw out of bounds error (the local source coordinate is -1) for protein, but cDNA starts from beginning and not at deletion start point
- [x] check same for downstream

**Apollo is not able to "Create Genomic Deletion" nor "Create Genomics Substitution" when the number of nucleotides to be deleted includes an intron/exon boundary.** 

For example in the figure below, notice that the cursor (yellow highlight on reference sequence) is located very close to the end of the exon. If the user enters the number "2" in the length of the deletion, the deletion will be created. If the user enters a number that exceeds the number of nucleotides left before the exon ends, Apollo will not create the deletion, and will not issue an error. The same is true when the deletion goes from an intron into an exon. (Note: remember that the length of the deletions are counted to the right of the cursor position, regardless of strand). The same is true for substitutions.

![screen shot 2015-06-25 at 4 56 16 pm](https://cloud.githubusercontent.com/assets/1714621/8368208/173cbab6-1b5c-11e5-9010-be94df021d34.png)

**Comment by nathandunn** [comment]
@deepakunni3   Do you have a minute to look at this?

**Comment by deepakunni3** [comment]
@nathandunn Sure. I can start with this one.

**Comment by deepakunni3** [comment]
@monicacecilia Can I get the name of the gene that is used in the image above.
I tried with couple of genes and the deletions are created at exon-intron boundary.

**Comment by nathandunn** [comment]
I remember it was on 1.33.

Nathan

**Comment by deepakunni3** [comment]
@nathandunn  Thanks!
Gene in question: **GB40031-RA** on Group 1.33

w.r.t. the current master branch, I can create deletions successfully at the exon-intron boundary.

**Comment by nathandunn** [comment]
Go ahead and close it.  Try on icebox first though?  Maybe a snafu? 

Nathan

**Comment by monicacecilia** [comment]
I am still unable to create substitutions. This is not a "snafu". I have sent an email to both of you with a video - GitHub does not support it.

**Comment by deepakunni3** [comment]
@monicacecilia Yes. Now I see the bug. Especially when adding sequence alterations that extends from intron - to - exon.

**Comment by nathandunn** [comment]
Appears to be working.

**Comment by nathandunn** [comment]
sorry . . didn't mean to close this.

**Comment by nathandunn** [comment]
Looks to be working now.

**Comment by monicacecilia** [comment]
Nope. The logic has now gone bananas.

After conducting an alteration to delete 12 nucleotides to the right of position 1,571,572, going from the intron into the exon.

![screen shot 2015-08-04 at 7 02 40 pm](https://cloud.githubusercontent.com/assets/1714621/9076775/8dbaa010-3adb-11e5-99b1-8a5fb0daad64.png)

The resulting gene model looks like this: 
![screen shot 2015-08-04 at 7 00 51 pm](https://cloud.githubusercontent.com/assets/1714621/9076749/3b4025f8-3adb-11e5-91ab-3c059c5081d4.png)

And when looking at the sequence (Get Sequence), there are exons of 1, 3, 19 residues long, where far longer exons are being visualized.

To reproduce:
- Go to Group16.4:1568401..1582440 (14.04 Kb) in the honey bee genome Apollo instance. 
- Standing in position 1,571,572 create a genomic insertion 12 nt long.

**Comment by nathandunn** [comment]
Going the other way, this is the error.   Should delete 5 residues, instead it is trying to do:

```
     println "START local coordinate ${localCoordinate} "
                    println "START current offset ${currentOffset} "
                    println "START - sequence alteration ${sequenceAlteration.length} "

                    println "END local coordinate ${localCoordinate} "
                    println "END current offset ${currentOffset} "

                    residues.delete(localCoordinate + currentOffset - sequenceAlteration.getLength() + 1,
                            localCoordinate + currentOffset + 1);
```

which gives:
```
START local coordinate 4 
START current offset 0 
START - sequence alteration 12 
END local coordinate 4 
END current offset 0 
```

I think what it should be is:

```
--- a/grails-app/services/org/bbop/apollo/SequenceService.groovy
+++ b/grails-app/services/org/bbop/apollo/SequenceService.groovy
@@ -103,15 +103,20 @@ class SequenceService {
             // Deletions
             else if (sequenceAlteration instanceof Deletion) {
                 if (strand == Strand.NEGATIVE) {
-                    residues.delete(localCoordinate + currentOffset - sequenceAlteration.getLength() + 1,
-                            localCoordinate + currentOffset + 1);
+                    if((localCoordinate + currentOffset) < sequenceAlteration.getLength() + 1 ){
+                        residues.delete(0, localCoordinate + currentOffset + 1);
+                    }
+                    else{
+                        residues.delete(localCoordinate + currentOffset - sequenceAlteration.getLength() + 1,
+                                localCoordinate + currentOffset + 1);
+                    }
                 } else {
 // TODO: fix this as well!!!
                     residues.delete(localCoordinate + currentOffset,
                             localCoordinate + currentOffset + sequenceAlteration.getLength());
                 }
                 currentOffset -= sequenceAlterationResidues.length();
             }
-            // Substitions
+            // Substitutions
```

<img width="319" alt="screen shot 2015-08-04 at 7 17 49 pm" src="https://cloud.githubusercontent.com/assets/751274/9076968/81914a3a-3add-11e5-8ccb-ad3157b8cbe4.png">

```
String index out of range: -7. Stacktrace follows:
Message: String index out of range: -7
    Line | Method
->>  694 | delete                                             in java.lang.AbstractStringBuilder
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    250 | delete                                             in java.lang.StringBuilder
|    107 | $tt__getGenomicResiduesFromSequenceWithAlterations in org.bbop.apollo.SequenceService
|    469 | $tt__getCodingSequenceInPhase                      in org.bbop.apollo.ExonService
|    289 | $tt__getSequenceForFeature . . . . . . . . . . . . in org.bbop.apollo.SequenceService
|    384 | $tt__getSequenceForFeatures                        in     ''
|    672 | getSequence . . . . . . . . . . . . . . . . . . .  in org.bbop.apollo.AnnotationEditorController
```

**Comment by nathandunn** [comment]
This offset is still of as well:

<img width="691" alt="screen shot 2015-08-04 at 7 44 49 pm" src="https://cloud.githubusercontent.com/assets/751274/9077310/83a6ec36-3ae1-11e5-968c-df9a86e85d5a.png">

The local coordinate is ```-1``` . .. ,but in reality it should be ```-4``` . . so it ends up not deleting far enough:
```
-                    residues.delete(localCoordinate + currentOffset,
-                            localCoordinate + currentOffset + sequenceAlteration.getLength());
+                    if(localCoordinate <0){
+                        residues.delete( currentOffset, currentOffset + sequenceAlteration.getLength());
+                    }
+                    else{
+                        residues.delete(localCoordinate + currentOffset,
+                                localCoordinate + currentOffset + sequenceAlteration.getLength());
+                    }
```

It should be:  12 - 4  = 8  . . . or sequenceAlteration.length - localCoordinate  .

**Comment by nathandunn** [comment]
The peptide sequence is also wrong:

<img width="589" alt="screen shot 2015-08-04 at 7 52 40 pm" src="https://cloud.githubusercontent.com/assets/751274/9077386/631fe2d2-3ae2-11e5-978b-9b1b4183bd43.png">

**Comment by nathandunn** [comment]
@monicacecilia, 

@deepakunni3  and I discovered that it is a problem ONLY with getting sequence off of subfeatures, but we think  the whole transcript is okay.  Will try to finish fixing this, this morning . . ..

**Comment by cmdcolin** [comment]
We added a fix here 9ed8d6b69164 that is important

Previously anything downstream of an alteration was badly calculated in the insertion case

**Comment by nathandunn** [comment]
Okay, I merged it in. 

Nathan

**Comment by monicacecilia** [comment]
Apollo is now able to create alterations across intron/exon boundaries. 
The sequence seems to be correctly generated (****crosses fingers****).
So, I am going to close this issue. 

### HOWEVER:
- when creating these alterations, the software is still having some difficulties correctly placing the warnings precisely under the offending boundary. In the figure below, the "non-canonical splice site" warning is drawn slightly offset from the actual boundary when Apollo correctly recalculated the CDS after the substitution.

<img width="159" alt="screen shot 2015-08-13 at 8 20 04 am" src="https://cloud.githubusercontent.com/assets/1714621/9253751/700d44b8-4194-11e5-9442-5008496fd8d9.png">

This is what the warning should look like (not the same place, but used for reference): 
<img width="101" alt="screen shot 2015-08-13 at 8 28 48 am" src="https://cloud.githubusercontent.com/assets/1714621/9253933/8a8ca440-4195-11e5-8277-3bc797034c76.png">

- @nathandunn Apollo is still changing the name of the transcript without user input. In this case, after "Undo" of a boundary modification, Apollo removed the name I had given the transcript and renamed it as the first transcript (xxxgenenamexxx-00001) from that gene model. I was working on gene model GB40030 in Group1.33. This has to do with #534 - and it is still not fixed.

**Comment by cmdcolin** [comment]
I noted the issue with things being slightly offset in my pull request #535 

I would like to revisit that placement as well so feel free to open a new issue for it. Good to close this one though

**Comment by monicacecilia** [comment]
Ah, thanks Colin. Yep, I'll open a new one.
